name: falcon
channels:
  - defaults
dependencies:
  - python=3.6
  - mpmath=1.3.0
  - numpy=1.26.3
  - scipy=1.12.0
  - setuptools=68.2.2
  - tabulate=0.9.0
  - urllib3=1.26.18
  - painy
  - black
  - ipython
