import urllib
from numpy import genfromtxt
from os import remove
import halcon
from time import time
from sys import exit
import cPickle as pickle

print '''
This example uses the HPA content database generated by

Murphy Lab
Dept. of Biological Sciences/Ray and Stephanie Lane Center for Computational Biology
Carnegie Mellon University
http://murphylab.web.cmu.edu
'''

url = 'http://murphylab.web.cmu.edu/software/searcher/proteinatlas.org-slf34-v4.pkl'
filename = 'hpa.pkl'
urllib.urlretrieve( url, filename )

data = pickle.load( file( filename, 'r' ) )
data = data[0.32]

print "I will use the first feature vector as my query image"
query_image = [[data[0][5], 10, data[0][12:]]]

print "\nAnd I will use the rest of the feature vectors to find the most similar images"
dataset = []
for datum in data:
	dataset.append([datum[5], 1, datum[12:]])

t = time()
[iids, scores] = halcon.search.query( query_image, dataset, normalization='standard', debug=True )
t = time() - t
print "Elapsed time: " + str(t) + " seconds\n"

iids = iids[:25]
scores = scores[:25]

outputfile = open('./index.html', 'w+')
outputfile.write('<html>')
outputfile.write('<body>')
outputfile.write('<h1>Human Protein Atlas</h1>')
outputfile.write('<h2>Query Image</h2>')
outputfile.write('<a href="' + str(query_image[0][0]) + '"><img src="' + str(query_image[0][0]) + '" width="50%" /></a>')
outputfile.write('<h2>Results</h2>')
outputfile.write('<table border="1" width="25%">')
outputfile.write('<tr><td>Score</td><td>Image</td></tr>')

for iid, score in zip(iids,scores):
	outputfile.write('<tr><td>')
	outputfile.write( str(score) + '</td><td align="center"><a href="' + str(iid) + '"><img src="' + str(iid) + '" width="50%" /></a>' )
	outputfile.write('</td></tr>')

outputfile.write('</table>')
outputfile.write('</body>')
outputfile.write('</html>')
outputfile.close()
