import urllib3
from numpy import genfromtxt
from os import remove
from halcon import search
from time import time
from sys import exit
import pandas as pd
import shutil

import ssl
ssl._create_default_https_context = ssl._create_unverified_context

print('''
This example uses the HPA content database generated by

Murphy Lab
Dept. of Biological Sciences/Ray and Stephanie Lane Center for Computational Biology
Carnegie Mellon University
http://murphylab.web.cmu.edu
''')

url = 'http://www.andrew.cmu.edu/~icaoberg/proteinatlas.org-slf34-v4.pkl'
filename = 'hpa.pkl'

http = urllib3.PoolManager()
with open(filename, 'wb') as out:
    r = http.request('GET', url, preload_content=False)
    shutil.copyfileobj(r, out)

data = pd.read_pickle( filename )
data = data[0.32]

print("I will use the first feature vector as my query image")
query_image = [[data[0][5], 10, data[0][12:]]]

print("\nAnd I will use the rest of the feature vectors to find the most similar images")
dataset = []
for datum in data:
	dataset.append([datum[5], 1, datum[12:]])

t = time()
[iids, scores] = search.query( query_image, dataset, normalization='standard', debug=True )
t = time() - t
print("Elapsed time: " + str(t) + " seconds\n")

iids = iids[:25]
scores = scores[:25]

outputfile = open('./index.html', 'w+')
outputfile.write('<html>')
outputfile.write('<body>')
outputfile.write('<h1>Human Protein Atlas</h1>')
outputfile.write('<h2>Query Image</h2>')
outputfile.write('<a href="' + str(query_image[0][0]) + '"><img src="' + str(query_image[0][0]) + '" width="50%" /></a>')
outputfile.write('<h2>Results</h2>')
outputfile.write('<table border="1" width="25%">')
outputfile.write('<tr><td>Score</td><td>Image</td></tr>')

for iid, score in zip(iids,scores):
	outputfile.write('<tr><td>')
	outputfile.write( str(score) + '</td><td align="center"><a href="' + str(iid) + '"><img src="' + str(iid) + '" width="50%" /></a>' )
	outputfile.write('</td></tr>')
outputfile.write('</table>')
outputfile.write('</body>')
outputfile.write('</html>')
outputfile.close()
